name: hackpsu
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.3
  formz: ^0.4.1
  form_validator: ^1.0.2
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.18
  firebase_storage: ^10.2.16
  provider: ^6.0.2

  http: ^0.13.4
  google_sign_in: ^5.3.1
  github_sign_in: ^0.0.5-dev.4
  flutter_svg: ^1.0.3

  bloc: ^8.0.3
  flutter_bloc: ^8.0.1

  # json serialization
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0
  build_runner: ^2.1.11

  # lottie
  lottie: ^1.3.0

  # qr code
  qr_flutter: ^4.0.0

  # collections
  collection: ^1.15.0

  # datetime
  intl: ^0.17.0
  timezone: ^0.8.0

  # persistent bloc
  hydrated_bloc: ^9.0.0-dev.3

  # filesystem
  path_provider: ^2.0.10

  # push notifications
  firebase_messaging: ^11.4.0
  flutter_local_notifications: ^9.5.3+1

  # Launcher Icons
  flutter_launcher_icons: ^0.9.2

  # SignIn with Apple
  the_apple_sign_in: ^1.1.1
  sign_in_with_apple: ^3.3.0

  # Sponsor Carousel
  carousel_slider: ^4.1.1

  # Websocket
  socket_io_client: ^2.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  url_launcher: ^6.1.2
  firebase_app_check: ^0.0.6+13

  # html parser
  html: ^0.15.0

  # Stream
  rxdart: ^0.27.5

  # Connectivity
  connectivity_plus: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path_ios: "assets/images/ios_app_icon.png"
  image_path_android: "assets/images/Logo.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/sponsors/
    - assets/icons/
    - assets/lottie/

  fonts:
    - family: Cornerstone
      fonts:
        - asset: assets/fonts/Cornerstone.ttf
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Regular.ttf
        - asset: assets/fonts/SpaceGrotesk-SemiBold.ttf
          weight: 600
    - family: PlexMono
      fonts:
        - asset: assets/fonts/IBMPlexMono-Medium.otf
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
