// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

User _$UserFromJson(Map<String, dynamic> json) => User(
      uid: json['uid'] as String?,
      firstname: json['firstname'] as String?,
      lastname: json['lastname'] as String?,
      gender: json['gender'] as String?,
      eighteenBeforeEvent: json['eighteen_before_event'] as bool?,
      shirtSize: json['shirt_size'] as String?,
      dietaryRestriction: json['dietary_restriction'] as String?,
      allergies: json['allergies'] as String?,
      travelReimbursement: json['travel_reimbursement'] as bool?,
      firstHackathon: json['first_hackathon'] as bool?,
      university: json['university'] as String?,
      email: json['email'] as String?,
      academicYear: json['academic_year'] as String?,
      major: json['major'] as String?,
      resume: json['resume'],
      mlhCoc: json['mlh_coc'] as bool?,
      mlhDcp: json['mlh_dcp'] as bool?,
      phone: json['phone'] as String?,
      address: json['address'] as String?,
      race: json['race'] as String?,
      codingExperience: json['coding_experience'] as String?,
      referral: json['referral'] as String?,
      project: json['project'] as String?,
      submitted: json['submitted'] as bool?,
      expectations: json['expectations'] as String?,
      veteran: json['veteran'] as String?,
      pin: json['pin'] as int?,
      shareAddressMlh: json['share_address_mlh'] as bool?,
      shareAddressSponsors: json['share_address_sponsors'] as bool?,
      time: User._timeFromJson(json['time'] as String),
      hackathon: json['hackathon'] as String?,
      name: json['name'] as String?,
      startTime: User._timeFromJson(json['start_time'] as String),
      endTime: User._timeFromJson(json['end_time'] as String),
      basePin: json['base_pin'] as int?,
      active: json['active'] as bool?,
      wordPin: json['word_pin'] as String,
    );

Map<String, dynamic> _$UserToJson(User instance) => <String, dynamic>{
      'uid': instance.uid,
      'firstname': instance.firstname,
      'lastname': instance.lastname,
      'gender': instance.gender,
      'eighteen_before_event': instance.eighteenBeforeEvent,
      'shirt_size': instance.shirtSize,
      'dietary_restriction': instance.dietaryRestriction,
      'allergies': instance.allergies,
      'travel_reimbursement': instance.travelReimbursement,
      'first_hackathon': instance.firstHackathon,
      'university': instance.university,
      'email': instance.email,
      'academic_year': instance.academicYear,
      'major': instance.major,
      'resume': instance.resume,
      'mlh_coc': instance.mlhCoc,
      'mlh_dcp': instance.mlhDcp,
      'phone': instance.phone,
      'address': instance.address,
      'race': instance.race,
      'coding_experience': instance.codingExperience,
      'referral': instance.referral,
      'project': instance.project,
      'submitted': instance.submitted,
      'expectations': instance.expectations,
      'veteran': instance.veteran,
      'pin': instance.pin,
      'share_address_mlh': instance.shareAddressMlh,
      'share_address_sponsors': instance.shareAddressSponsors,
      'time': instance.time.toIso8601String(),
      'hackathon': instance.hackathon,
      'name': instance.name,
      'start_time': instance.startTime.toIso8601String(),
      'end_time': instance.endTime.toIso8601String(),
      'base_pin': instance.basePin,
      'active': instance.active,
      'word_pin': instance.wordPin,
    };
